import '../styles/globals.css'
import Header from './Header'

export const metadata = {
  title: 'Meta messenger',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body>
      <Header></Header>
        
        {children}
        
        
        </body>
    </html>
  )
}
